name: Test

on:
  push:
    branches:
      - master

env:
  MIX_ENV: test

jobs:
  check-formatted:
    name: Check formatted
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - run: mix deps.get
      - run: mix compile

      - run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - run: mix deps.get
      - run: mix compile

      - run: mix test